// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MeterUsageServiceClient is the client API for MeterUsageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MeterUsageServiceClient interface {
	Get(ctx context.Context, in *MeterUsageRequest, opts ...grpc.CallOption) (*MeterUsageResponse, error)
}

type meterUsageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMeterUsageServiceClient(cc grpc.ClientConnInterface) MeterUsageServiceClient {
	return &meterUsageServiceClient{cc}
}

func (c *meterUsageServiceClient) Get(ctx context.Context, in *MeterUsageRequest, opts ...grpc.CallOption) (*MeterUsageResponse, error) {
	out := new(MeterUsageResponse)
	err := c.cc.Invoke(ctx, "/proto.MeterUsageService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MeterUsageServiceServer is the server API for MeterUsageService service.
// All implementations must embed UnimplementedMeterUsageServiceServer
// for forward compatibility
type MeterUsageServiceServer interface {
	Get(context.Context, *MeterUsageRequest) (*MeterUsageResponse, error)
	mustEmbedUnimplementedMeterUsageServiceServer()
}

// UnimplementedMeterUsageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMeterUsageServiceServer struct {
}

func (UnimplementedMeterUsageServiceServer) Get(context.Context, *MeterUsageRequest) (*MeterUsageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedMeterUsageServiceServer) mustEmbedUnimplementedMeterUsageServiceServer() {}

// UnsafeMeterUsageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MeterUsageServiceServer will
// result in compilation errors.
type UnsafeMeterUsageServiceServer interface {
	mustEmbedUnimplementedMeterUsageServiceServer()
}

func RegisterMeterUsageServiceServer(s grpc.ServiceRegistrar, srv MeterUsageServiceServer) {
	s.RegisterService(&MeterUsageService_ServiceDesc, srv)
}

func _MeterUsageService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MeterUsageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MeterUsageServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.MeterUsageService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MeterUsageServiceServer).Get(ctx, req.(*MeterUsageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MeterUsageService_ServiceDesc is the grpc.ServiceDesc for MeterUsageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MeterUsageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.MeterUsageService",
	HandlerType: (*MeterUsageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Get",
			Handler:    _MeterUsageService_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/meterusage.proto",
}
